### ISSUE TITLE
Add an option to remove md5 hash on assets filename

### ISSUE THREAD

**Issue by thibaudgg** [dnagir/guard-rails-assets#12]
Hi,

I use `guard-rails-assets` with `guard-jasmine-headless-webkit` and Guard can't detect new created files if they are created during the same second of a guard execution (Ruby file mtime is second accurate) and because of the md5 hash, new assets files always get a new name (Guard use a lazy loaded 'md5 hash' list for  **already existing** files to detect modification during the same second). So it would be great to have an option to remove these md5 hash with `guard-rails-assets`.

@dnagir has already tried [here](https://github.com/mcolyer/guard-rails-assets/commit/4096407a7a27711011bba1e6cc833d27af8ee9ce) but it is not working for me.

I hope it's not too bad explained. What do you think about this option?

**Comment by dnagir** [comment]
I am not sure yet if I want to introduce this option because the issue with file name is easily solvable by adding wildcard.

http://dev.approache.com/testing-your-javascript/#slide18

Fo example:

``` yaml
src_files:
  - public/assets/first-priority-files-*.js
  - public/assets/application-*.js
  - public/assets/**/*.js
helpers:
  - helpers/**/*.js
  - compiled/helpers/*.js
spec_files:
  - '**/*[sS]pec.js'
```
